In [4]:
import pandas as pd

# Load RNA-RNA interaction file
file_path = "RNAInter_RNA_RNA.txt"

# Try common delimiters (RNAInter files are usually tab-delimited)
df = pd.read_csv(file_path, sep='\t', low_memory=False)

# Display basic info
print(f"Number of interactions: {len(df)}")
df.head()

Number of interactions: 9484609

,RNAInterID,Interactor1.Symbol,Category1,Species1,Interactor2.Symbol,Category2,Species2,Raw_ID1,Raw_ID2,score,strong,weak,predict
0,RR00000169,(Ca)N,repeats,Mus musculus,B1_Mus1,repeats,Mus musculus,chr4(CA)n125049227,chr15B1_Mus136600585,0.23,NaN,MARIO,NaN
1,RR00000238,(Ca)N,repeats,Mus musculus,B1_Mus1,repeats,Mus musculus,chr8(CA)n67899847,chr8B1_Mus167899573,0.23,NaN,MARIO,NaN
2,RR00000198,(Ca)N,repeats,Mus musculus,B1_Mus1,repeats,Mus musculus,chr6(CA)n135011645,chr6B1_Mus1135012241,0.23,NaN,MARIO,NaN
3,RR00000231,(Ca)N,repeats,Mus musculus,B1_Mus1,repeats,Mus musculus,chr8(CA)n114753246,chr8B1_Mus1114753067,0.23,NaN,MARIO,NaN
4,RR00000249,(Ca)N,repeats,Mus musculus,B3,repeats,Mus musculus,chr9(CA)n21755504,chr9B321755686,0.23,NaN,MARIO,NaN

In [5]:
# Show column names
print("Columns:", df.columns.tolist())

# Inspect data types
df.dtypes

Columns: ['RNAInterID', 'Interactor1.Symbol', 'Category1', 'Species1', 'Interactor2.Symbol', 'Category2', 'Species2', 'Raw_ID1', 'Raw_ID2', 'score', 'strong', 'weak', 'predict']

RNAInterID             object
Interactor1.Symbol     object
Category1              object
Species1               object
Interactor2.Symbol     object
Category2              object
Species2               object
Raw_ID1                object
Raw_ID2                object
score                 float64
strong                 object
weak                   object
predict                object
dtype: object

In [6]:
# Check unique categories in both interactors
cat1_unique = df['Category1'].unique()
cat2_unique = df['Category2'].unique()

# Optionally, combined unique categories across both columns
combined_categories = set(cat1_unique) | set(cat2_unique)
print("All unique RNA categories in dataset:", combined_categories)

All unique RNA categories in dataset: {'scRNA', 'snRNA', 'TR_C_gene', 'miRNA', 'circRNA', 'tRNA', 'ncRNA', 'antisense', 'lincRNA', 'processed_transcript', 'repeats', 'piRNA', 'Category2', 'protein', 'unknown', 'tRF', 'Category1', 'TEC', 'ribozyme', 'unassigned RNA', 'PCG', 'Protein', 'mRNA', 'sncRNA', 'TF', 'scaRNA', 'snoRNA', 'rRNA', 'others', 'sRNA', 'miscRNA', 'shRNA', 'pseudo', 'eRNA', 'lncRNA'}

In [7]:
df_mRNA = df[(df['Category1'] == 'mRNA') | (df['Category2'] == 'mRNA')]
print(f"Rows after keeping mRNA: {len(df_mRNA)}")

df_mRNA

Rows after keeping mRNA: 9253466

,RNAInterID,Interactor1.Symbol,Category1,Species1,Interactor2.Symbol,Category2,Species2,Raw_ID1,Raw_ID2,score,strong,weak,predict
98,RR00000081,(Ca)N,repeats,Mus musculus,Sacm1l,mRNA,Mus musculus,chr12(CA)n86725649,NCBI:83493,0.2300,NaN,MARIO,NaN
99,RR00000180,(Ca)N,repeats,Mus musculus,Sacm1l,mRNA,Mus musculus,chr5(CA)n113846835,NCBI:83493,0.2300,NaN,MARIO,NaN
100,RR00000167,(Ca)N,repeats,Mus musculus,Sacm1l,mRNA,Mus musculus,chr3(CA)n83375276,NCBI:83493,0.2300,NaN,MARIO,NaN
101,RR00000087,(Ca)N,repeats,Mus musculus,Sacm1l,mRNA,Mus musculus,chr13(CA)n29980063,NCBI:83493,0.2300,NaN,MARIO,NaN
102,RR00000216,(Ca)N,repeats,Mus musculus,Sacm1l,mRNA,Mus musculus,chr7(CA)n141447615,NCBI:83493,0.2300,NaN,MARIO,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...
9484604,RR09489264,tRF-5046,tRF,Danio rerio,zzz3,mRNA,Danio rerio,tRFdb:tRF-5046,NCBI:567022,0.2131,NaN,NaN,RNAhybrid
9484605,RR09489265,tRF-5048,tRF,Danio rerio,zzz3,mRNA,Danio rerio,tRFdb:tRF-5048,NCBI:567022,0.3150,NaN,NaN,RNAhybrid//IntaRNA
9484606,RR09489266,tRF-5050,tRF,Danio rerio,zzz3,mRNA,Danio rerio,tRFdb:tRF-5050,NCBI:567022,0.3150,NaN,NaN,RNAhybrid//IntaRNA
9484607,RR09489267,tRF-5054,tRF,Danio rerio,zzz3,mRNA,Danio rerio,tRFdb:tRF-5054,NCBI:567022,0.2131,NaN,NaN,RNAhybrid
9484608,RR09489268,tRF-5057,tRF,Danio rerio,zzz3,mRNA,Danio rerio,tRFdb:tRF-5057,NCBI:567022,0.2131,NaN,NaN,RNAhybrid

In [8]:
exclude_categories = {'Category1', 'Category2', 'unknown', 'unassigned RNA', 'others', 'Protein', 'protein',
                      'PCG', # Protein-coding Gene
                      'TF', # transcription factor gene
                      'TR_C_gene', # T-cell receptor constant region gene; immune-related.
                      'antisense', # transcripts complementary to sense strands of annotated genes.
                      'TEC', # “to be experimentally confirmed,” provisional transcripts.
                      'repeats' # transcripts overlapping repetitive genomic elements.
                     }

# Filter out unwanted categories from both interactors
df_filt = df[~df['Category1'].isin(exclude_categories) & ~df['Category2'].isin(exclude_categories)]

print(f"Rows after removing not-clear categories: {len(df_filt)}")

Rows after removing not-clear categories: 9429474

In [9]:
# Check unique categories in both interactors
cat1_unique = df_filt['Category1'].unique()
cat2_unique = df_filt['Category2'].unique()

# Optionally, combined unique categories across both columns
combined_categories = set(cat1_unique) | set(cat2_unique)
print("All unique RNA categories in dataset:", combined_categories)

All unique RNA categories in dataset: {'scRNA', 'snRNA', 'miRNA', 'circRNA', 'tRNA', 'ncRNA', 'lincRNA', 'processed_transcript', 'piRNA', 'tRF', 'ribozyme', 'mRNA', 'sncRNA', 'scaRNA', 'snoRNA', 'rRNA', 'miscRNA', 'sRNA', 'shRNA', 'pseudo', 'eRNA', 'lncRNA'}

In [10]:
# filter nan
print(f"RNA–RNA interactions: {len(df_filt)}")
df_filt = df_filt.dropna(subset=['Raw_ID1', 'Raw_ID2'])
print(f"RNA–RNA interactions: {len(df_filt)}")

RNA–RNA interactions: 9429474
RNA–RNA interactions: 8976390

In [11]:
parsed = []

def parse_ids(id_value):
    if pd.isna(id_value):
        return [None]
    elif ':' in id_value:
        prefix, ids_str = id_value.split(':', 1)
        return [f"{prefix}:{id_.strip()}" for id_ in ids_str.split(';')]
    else:
        parsed.append(id_value)
        return [id_value.strip()]

# Add list columns
df_filt['Raw_ID1_list'] = df_filt['Raw_ID1'].apply(parse_ids)
df_filt['Raw_ID2_list'] = df_filt['Raw_ID2'].apply(parse_ids)

In [12]:
parsed

[]

In [13]:
print(f"RNA–RNA interactions: {len(df_filt)}")

RNA–RNA interactions: 8976390

In [14]:
df_filt.head()

,RNAInterID,Interactor1.Symbol,Category1,Species1,Interactor2.Symbol,Category2,Species2,Raw_ID1,Raw_ID2,score,strong,weak,predict,Raw_ID1_list,Raw_ID2_list
3638,RR00670755,Gm24029,snoRNA,Mus musculus,U5,snRNA,Mus musculus,Ensembl:ENSMUSG00000065862,Ensembl:ENSMUSG00000070228,0.23,NaN,MARIO,NaN,[Ensembl:ENSMUSG00000065862],[Ensembl:ENSMUSG00000070228]
3639,RR00670756,Gm24029,snoRNA,Mus musculus,U5,snRNA,Mus musculus,Ensembl:ENSMUSG00000065862,Ensembl:ENSMUSG00000075763,0.23,NaN,MARIO,NaN,[Ensembl:ENSMUSG00000065862],[Ensembl:ENSMUSG00000075763]
3640,RR00670754,Gm24029,snoRNA,Mus musculus,U5,snRNA,Mus musculus,Ensembl:ENSMUSG00000065862,Ensembl:ENSMUSG00000064881,0.23,NaN,MARIO,NaN,[Ensembl:ENSMUSG00000065862],[Ensembl:ENSMUSG00000064881]
3641,RR00673515,Gm24455,snoRNA,Mus musculus,U5,snRNA,Mus musculus,Ensembl:ENSMUSG00000065282,Ensembl:ENSMUSG00000064430,0.23,NaN,MARIO,NaN,[Ensembl:ENSMUSG00000065282],[Ensembl:ENSMUSG00000064430]
3642,RR00673516,Gm24455,snoRNA,Mus musculus,U5,snRNA,Mus musculus,Ensembl:ENSMUSG00000065282,Ensembl:ENSMUSG00000064881,0.23,NaN,MARIO,NaN,[Ensembl:ENSMUSG00000065282],[Ensembl:ENSMUSG00000064881]

In [15]:
# we need to standardise the species to TAXIDs

In [16]:
# 1. See unique species
df_filt.replace({'-': None}, inplace=True)
unique_species = pd.unique(df_filt[['Species1', 'Species2']].values.ravel())
print("Unique species:", len(unique_species))

from ete3 import NCBITaxa
ncbi = NCBITaxa()

unique_species_taxids = {}
missing = []

for test_species in unique_species:
    # Skip placeholders
    if test_species in [None]:
        continue

    # Handle known special cases first
    if test_species == 'Solanum tuberosum L.':
        unique_species_taxids[test_species] = "4113"
        continue
    if test_species == 'Rhodobacter sphaeroides ATCC 17025':
        unique_species_taxids[test_species] = "1061"
        continue

    # Query NCBI
    try:
        taxid = str(ncbi.get_name_translator([test_species])[test_species][0])
        unique_species_taxids[test_species] = taxid
    except KeyError:
        missing.append(test_species)

print("Mapped species (unique -1 for None):", len(unique_species_taxids))
print("Missing species:", missing)

Unique species: 98
Mapped species (unique -1 for None): 97
Missing species: []

In [17]:
# Assume df is your original dataframe
# unique_species_taxids: dict {species_name -> taxid}

df_filt['Species1_TaxID'] = df_filt['Species1'].map(unique_species_taxids)
df_filt['Species2_TaxID'] = df_filt['Species2'].map(unique_species_taxids)

unmapped_s1 = df_filt.loc[df_filt['Species1'].notna() & df_filt['Species1_TaxID'].isna(), 'Species1'].unique()
unmapped_s2 = df_filt.loc[df_filt['Species2'].notna() & df_filt['Species2_TaxID'].isna(), 'Species2'].unique()

print("Unmapped Species1:", unmapped_s1)
print("Unmapped Species2:", unmapped_s2)

Unmapped Species1: []
Unmapped Species2: []

In [18]:
# removing NAN
df_filt = df_filt.dropna(subset=['Species1_TaxID', 'Species2_TaxID'])

In [19]:
# Check unique categories in both interactors
cat1_unique = df_filt['Category1'].unique()
cat2_unique = df_filt['Category2'].unique()

# Optionally, combined unique categories across both columns
combined_categories = set(cat1_unique) | set(cat2_unique)
print("All unique RNA categories in dataset:", combined_categories)

RNA_TYPE_MAP = {
    'processed_transcript': 'ncRNA',
    'miscRNA': 'ncRNA',
}

# Apply standardisation
df_filt['Category1_std'] = df_filt['Category1'].replace(RNA_TYPE_MAP)
df_filt['Category2_std'] = df_filt['Category2'].replace(RNA_TYPE_MAP)

# Recompute unique categories after mapping
cat1_std = set(df_filt['Category1_std'].unique())
cat2_std = set(df_filt['Category2_std'].unique())

print("Standardised categories:", cat1_std | cat2_std)

assert not df_filt[['Category1_std', 'Category2_std']].isna().any().any()

All unique RNA categories in dataset: {'scRNA', 'snRNA', 'miRNA', 'mRNA', 'circRNA', 'tRNA', 'ncRNA', 'sncRNA', 'scaRNA', 'processed_transcript', 'lincRNA', 'snoRNA', 'rRNA', 'piRNA', 'sRNA', 'miscRNA', 'tRF', 'pseudo', 'lncRNA', 'ribozyme'}
Standardised categories: {'scRNA', 'snRNA', 'miRNA', 'mRNA', 'circRNA', 'tRNA', 'ncRNA', 'sncRNA', 'scaRNA', 'lincRNA', 'snoRNA', 'rRNA', 'piRNA', 'sRNA', 'tRF', 'pseudo', 'lncRNA', 'ribozyme'}

In [20]:
df_filt.keys()

Index(['RNAInterID', 'Interactor1.Symbol', 'Category1', 'Species1',
       'Interactor2.Symbol', 'Category2', 'Species2', 'Raw_ID1', 'Raw_ID2',
       'score', 'strong', 'weak', 'predict', 'Raw_ID1_list', 'Raw_ID2_list',
       'Species1_TaxID', 'Species2_TaxID', 'Category1_std', 'Category2_std'],
      dtype='object')

In [21]:
# DATASET IS READY.
# df_filt keys: Index(['RNAInterID', 'Interactor1.Symbol', 'Category1', 'Species1',
#       'Interactor2.Symbol', 'Category2', 'Species2', 'Raw_ID1', 'Raw_ID2',
#       'score', 'strong', 'weak', 'predict', 'Raw_ID1_list', 'Raw_ID2_list'],
#      dtype='object')

'''
Index(['RNAInterID', 'Interactor1.Symbol', 'Category1', 'Species1',
       'Interactor2.Symbol', 'Category2', 'Species2', 'Raw_ID1', 'Raw_ID2',
       'score', 'strong', 'weak', 'predict', 'Raw_ID1_list', 'Raw_ID2_list',
       'Species1_TaxID', 'Species2_TaxID'],
      dtype='object')
'''

# Now we need to extract sequences, we start by taking unique of ('Interactor1.Symbol', 'Category1', 'Species1_TaxID', 'Raw_ID1_list')
# We do not care about 1 and 2, we can create the final database later.

def normalize_id_list(x):
    if isinstance(x, list):
        return tuple(sorted(str(i) for i in x if i is not None))
    return tuple()
df_filtbackup = df_filt

df_filt = df_filt.copy()
df_filt['Raw_ID1_key'] = df_filt['Raw_ID1_list'].apply(normalize_id_list)
df_filt['Raw_ID2_key'] = df_filt['Raw_ID2_list'].apply(normalize_id_list)

rna_entities_1 = (
    df_filt.loc[:, ['Interactor1.Symbol', 'Category1', 'Species1_TaxID', 'Raw_ID1_key']]
    .drop_duplicates()
    .rename(columns={
        'Interactor1.Symbol': 'Symbol',
        'Category1': 'Category',
        'Species1_TaxID': 'Species',
        'Raw_ID1_key': 'Raw_ID_key'
    })
)

rna_entities_2 = (
    df_filt.loc[:, ['Interactor2.Symbol', 'Category2', 'Species2_TaxID', 'Raw_ID2_key']]
    .drop_duplicates()
    .rename(columns={
        'Interactor2.Symbol': 'Symbol',
        'Category2': 'Category',
        'Species2_TaxID': 'Species',
        'Raw_ID2_key': 'Raw_ID_key'
    })
)

rna_entities = (
    pd.concat([rna_entities_1, rna_entities_2], ignore_index=True)
    .drop_duplicates()
)

print(f"Unique RNA entities: {len(rna_entities)}")

rna_entities['RNA_IDs'] = rna_entities['Raw_ID_key'].apply(list)

def classify_ids(id_list):
    return {
        'miRBase': [],
        'NCBI': [],
        'Ensembl': [],
        'circBase': [],
        'tRFdb': [],
        'GenBank': [],
        'Other': [],
        'RNAcentral': []   # ← to be filled after resolution
    }

def populate_buckets(id_list):
    buckets = classify_ids(id_list)
    for rid in id_list:
        if rid.startswith('miRBase:'):
            buckets['miRBase'].append(rid.split(':', 1)[1])
        elif rid.startswith('NCBI:'):
            buckets['NCBI'].append(rid.split(':', 1)[1])
        elif rid.startswith('Ensembl:'):
            buckets['Ensembl'].append(rid.split(':', 1)[1])
        elif rid.startswith('circBase:'):
            buckets['circBase'].append(rid.split(':', 1)[1])
        elif rid.startswith('tRFdb:'):
            buckets['tRFdb'].append(rid.split(':', 1)[1])
        elif rid.startswith('GenBank:'):
            buckets['GenBank'].append(rid.split(':', 1)[1])
        else:
            buckets['Other'].append(rid)
    return buckets

rna_entities['ID_buckets'] = rna_entities['RNA_IDs'].apply(populate_buckets)

Unique RNA entities: 241559

In [22]:
rna_entities

,Symbol,Category,Species,Raw_ID_key,RNA_IDs,ID_buckets
0,Gm24029,snoRNA,10090,"(Ensembl:ENSMUSG00000065862,)",[Ensembl:ENSMUSG00000065862],"{'miRBase': [], 'NCBI': [], 'Ensembl': ['ENSMU..."
1,Gm24455,snoRNA,10090,"(Ensembl:ENSMUSG00000065282,)",[Ensembl:ENSMUSG00000065282],"{'miRBase': [], 'NCBI': [], 'Ensembl': ['ENSMU..."
2,Gm24616,snoRNA,10090,"(Ensembl:ENSMUSG00000065208,)",[Ensembl:ENSMUSG00000065208],"{'miRBase': [], 'NCBI': [], 'Ensembl': ['ENSMU..."
3,Gm24888,snoRNA,10090,"(Ensembl:ENSMUSG00000077575,)",[Ensembl:ENSMUSG00000077575],"{'miRBase': [], 'NCBI': [], 'Ensembl': ['ENSMU..."
4,Gm26109,snoRNA,10090,"(Ensembl:ENSMUSG00000065904,)",[Ensembl:ENSMUSG00000065904],"{'miRBase': [], 'NCBI': [], 'Ensembl': ['ENSMU..."
...,...,...,...,...,...,...
278862,zym1,mRNA,4896,"(NCBI:2541743,)",[NCBI:2541743],"{'miRBase': [], 'NCBI': ['2541743'], 'Ensembl'..."
278863,zyx,mRNA,7955,"(NCBI:564246,)",[NCBI:564246],"{'miRBase': [], 'NCBI': ['564246'], 'Ensembl':..."
278864,zzef1,mRNA,7955,"(NCBI:566682,)",[NCBI:566682],"{'miRBase': [], 'NCBI': ['566682'], 'Ensembl':..."
278865,zzef1,mRNA,8364,"(NCBI:100487543,)",[NCBI:100487543],"{'miRBase': [], 'NCBI': ['100487543'], 'Ensemb..."
278866,zzz3,mRNA,7955,"(NCBI:567022,)",[NCBI:567022],"{'miRBase': [], 'NCBI': ['567022'], 'Ensembl':..."

In [23]:
from collections import defaultdict

# Initialize counter
db_counts = defaultdict(int)

for buckets in rna_entities['ID_buckets']:
    for db, ids in buckets.items():
        if db != 'RNAcentral':  # exclude placeholder
            db_counts[db] += len(set(ids))  # count unique IDs per entity

# Print summary
for db, count in db_counts.items():
    print(f"{db}: {count} unique IDs across entities")

miRBase: 10975 unique IDs across entities
NCBI: 220820 unique IDs across entities
Ensembl: 8602 unique IDs across entities
circBase: 258 unique IDs across entities
tRFdb: 928 unique IDs across entities
GenBank: 3 unique IDs across entities
Other: 0 unique IDs across entities

In [13]:
'''
To-discuss: Assumption: 
all annotated isoforms (transcripts) of a gene are considered potential interactors 
when RNAInter reports a gene-level interaction.

We could think of some filters on the isoforms. For now we download them all, and keep track of isoforms-per-interaction (A list of sequences)
'''

'\nTo-discuss: Assumption: \nall annotated isoforms (transcripts) of a gene are considered potential interactors \nwhen RNAInter reports a gene-level interaction.\n\nWe could think of some filters on the isoforms. For now we download them all, and keep track of isoforms-per-interaction (A list of sequences)\n'

In [1]:
# Construct DUCK-DB based on RNAcentral BEFORE this step!!
import sys
sys.path.append("rnacentral-etl")

from rnacentral import QueryRnaCentral

qrc = QueryRnaCentral(base_dir="rnacentral_data/current_release", db_path="rnacentral-etl/rnacentral.duckdb")

In [2]:
ensembl_id = "ENST00000618786"  # example
print(f"\nEnsembl to RNAcentral (Ensembl ID={ensembl_id}):")
df_ens = qrc.ensembl_to_rnacentral(ensembl_id)
print(df_ens)

taxid= "9606"
ensembl_id = "ENST00000618786"  # example
print(f"\nEnsembl to RNAcentral (Ensembl ID={ensembl_id, taxid}):")
df_ens = qrc.ensembl_to_rnacentral(ensembl_id, taxid)
print(df_ens)

Ensembl to RNAcentral (Ensembl ID=ENST00000618786):
   RNAcentral_ID rna_type  taxid               misc
0  URS00000478B7  SRP_RNA   9606  ENSG00000276168.1

Ensembl to RNAcentral (Ensembl ID=('ENST00000618786', '9606')):
   RNAcentral_ID rna_type  taxid               misc
0  URS00000478B7  SRP_RNA   9606  ENSG00000276168.1

In [51]:
# Given this dataframe: rna_entities
# add 1 new column: RNACENTRAL_IDs
# we start with ENSEMBLE, in each row check if there is ensemble in the rna_entities['ID_buckets']['Ensembl'], it is a list,
# so for each ENSEMBLE ID in the list run a query: 
# df_ens = qrc.ensembl_to_rnacentral(ensembl_id, taxid)
# and we save a list in RNACENTRAL_IDs

In [3]:
 qrc.ensembl_to_rnacentral('ENSMUST00000083928') #ENSMUSG00000065862

# THE PROBLEM IS THAT ENSEMBLE IDS COULD BE GENES OR TRANSCRIPTS, 
# WE HAVE THE MAPPINGS IN ENACENTRAL ENSEMBL, They ARE IN THE MISC COLUMN!!
#

   RNAcentral_ID rna_type  taxid                  misc
0  URS0000639553   snoRNA  10090  ENSMUSG00000065862.3

In [29]:
def get_rnacentral_ids(row):
   
    rnacentral_ids = set()

    ensembl_ids = row.get("ID_buckets", {}).get("Ensembl", [])
    taxid = row.get("Species")
    if not ensembl_ids:
        return []

    print(row)
    print(taxid)
    print(ensembl_ids)
    
    for ensembl_id in ensembl_ids:
        print(ensembl_id)
        try:
            df_ens = qrc.ensembl_to_rnacentral(ensembl_id, taxid)
            print(df_ens)
            os.exit(9)
            if df_ens is not None and not df_ens.empty:
                rnacentral_ids.update(df_ens["rnacentral_id"].dropna().tolist())
        except Exception:
            os.exit(9)
            continue

    return list(rnacentral_ids)


rna_entities["RNACENTRAL_IDs"] = rna_entities.apply(
    get_rnacentral_ids, axis=1
)

Symbol                                                  Gm24029
Category                                                 snoRNA
Species                                                   10090
Raw_ID_key                        (Ensembl:ENSMUSG00000065862,)
RNA_IDs                            [Ensembl:ENSMUSG00000065862]
ID_buckets    {'miRBase': [], 'NCBI': [], 'Ensembl': ['ENSMU...
Name: 0, dtype: object
10090
['ENSMUSG00000065862']
ENSMUSG00000065862
Empty DataFrame
Columns: [RNAcentral_ID, rna_type, taxid]
Index: []

NameError: name 'os' is not defined

In [ ]:
# X MIRNA:
from Bio import SeqIO

# Data structure: precursor_accession -> list of dicts with mature miRNA info
precursor_to_mature = {}

for record in SeqIO.parse("miRNA.dat", "embl"):
    precursor_acc = record.name  # e.g. MI0000001
    record_mir_id = record.id
    mature_list = []
    for feature in record.features:
        if feature.type in ("miRNA", "mature_miRNA"):            
            # extract sequence from location on precursor
            mature_seq = feature.location.extract(record).seq
            mature_seq = mature_seq.upper().replace("T", "U")
            mature_list.append(
                {
                "mature_id": mature_id,
                "sequence": str(mature_seq)
                }
            )
    if mature_list:
        precursor_to_mature[record_mir_id] = mature_list


precursor_to_mature = {}
mature_to_sequence  = {}

for record in SeqIO.parse("miRNA.dat", "embl"):
    pre_acc = record.id
    for feature in record.features:
        if feature.type not in ("miRNA","mature_miRNA"):
            continue

        seq = feature.location.extract(record).seq.upper().replace("T","U")
        quals = feature.qualifiers

        # pull MIMAT… from 'accession' qualifier
        mat_acc = quals.get("accession", [None])[0]
        # fallback if needed
        if not mat_acc:
            mat_acc = quals.get("note", [""])[0]

        precursor_to_mature.setdefault(pre_acc, []).append(str(seq))
        if mat_acc:
            mature_to_sequence.setdefault(mat_acc, []).append(str(seq))


mirbase_ids_to_sequence_list = []
for mid in mirbase_ids:
    if mid.startswith("MIMAT"):
        seqs = mature_to_sequence.get(mid, [])
    else:
        seqs = precursor_to_mature.get(mid, [])
    mirbase_ids_to_sequence_list.append({"mirbase_id": mid, "sequences": seqs})


# strip the "miRBase:" prefix to get the MI… or MIMAT… IDs
df_mi["id1"] = df_mi["Raw_ID1"].str.replace(r"^miRBase:", "", regex=True)
df_mi["id2"] = df_mi["Raw_ID2"].str.replace(r"^miRBase:", "", regex=True)

# map Raw_ID1/Raw_ID2 to sequence lists
id_to_seqs = {**precursor_to_mature, **mature_to_sequence}
df_mi["seq1_list"] = df_mi["id1"].map(lambda x: id_to_seqs.get(x, []))
df_mi["seq2_list"] = df_mi["id2"].map(lambda x: id_to_seqs.get(x, []))

In [64]:
# NOW THAT WE HAVE ALL THE IDS AND CORRESPONDING SEQUENCES,
# WE Drop rows with missing sequences

df_expanded = df_expanded.dropna(subset=["seq1", "seq2"])
df_expanded = df_expanded[(df_expanded["seq1"] != "") & (df_expanded["seq2"] != "")]
print(len(df_expanded))

3042